---
platform: win64 
generator-platform: x64
build_tool: vscode_cmake
build_type: Debug
defines:
    N_USE_VULKAN: ON
    __X64__: ON
    N_DEBUG_SYMBOLS: ON
    PX_TARGET: win.x86_64.vc143.md
vscode_exclude_from_workspace: 
    [
        #nebula-toolkit,
        fips-curl,
        fips-compressonator,
        fips-sqlite3,
        gliml,
        fips-flatbuffers,
        physx,
        nebula-libs,
        fips-zlib,
        fips-soloud,
        fips-stb,
        fips-pybind11,
        fips-imgui,
        fips-stackwalker,
        fips-devil,
        fips-lua,
        fips-libpng,
        fips-libjpeg,
        fips-anyfx,
        fips-vulkanheaders,
        fips-glew,
        fips-glslang,
        fips-glfw
    ]