---
platform: win64 
generator-platform: x64
build_tool: cmake
build_type: Release
defines:
    N_USE_VULKAN: ON
    N_USE_CHECKED_PHYSX: ON
    FIPS_MSVC_LTCG: OFF
    N_DEBUG_SYMBOLS: ON
    PX_TARGET: win.x86_64.vc143.md
    SOLOUD_BACKEND_WASAPI: ON
    SOLOUD_BACKEND_NULL: OFF
